#!/usr/bin/env node

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const rootDir = resolve(fileURLToPath(new URL('..', import.meta.url)))
const packageJson = JSON.parse(readFileSync(resolve(rootDir, 'package.json'), 'utf8'))
const packageLockJson = JSON.parse(readFileSync(resolve(rootDir, 'package-lock.json'), 'utf8'))
const outputPath = resolve(rootDir, 'src/generated/thirdPartyLicenses.ts')
const dependencyNotices = {
  '@capgo/capacitor-inappbrowser': (version) => ({
    sourceUrl: `https://github.com/Cap-go/capacitor-inappbrowser/tree/${version}`,
    licenseUrl: `https://github.com/Cap-go/capacitor-inappbrowser/blob/${version}/LICENSE`,
  }),
}

function readInstalledPackageMetadata(packageName) {
  const packagePath = resolve(rootDir, 'node_modules', packageName, 'package.json')
  if (!existsSync(packagePath)) {
    return null
  }

  return JSON.parse(readFileSync(packagePath, 'utf8'))
}

function resolveLicense(packageName) {
  const lockMetadata = packageLockJson.packages?.[`node_modules/${packageName}`]
  if (typeof lockMetadata?.license === 'string' && lockMetadata.license.trim()) {
    return lockMetadata.license.trim()
  }

  const installedMetadata = readInstalledPackageMetadata(packageName)
  if (typeof installedMetadata?.license === 'string' && installedMetadata.license.trim()) {
    return installedMetadata.license.trim()
  }

  throw new Error(`Unable to determine production dependency license: ${packageName}`)
}

function resolveVersion(packageName) {
  const lockMetadata = packageLockJson.packages?.[`node_modules/${packageName}`]
  if (typeof lockMetadata?.version === 'string' && lockMetadata.version.trim()) {
    return lockMetadata.version.trim()
  }

  throw new Error(`Unable to determine production dependency version: ${packageName}`)
}

function quote(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

const dependencyItems = Object.keys(packageJson.dependencies ?? {})
  .sort((left, right) => left.localeCompare(right))
  .map((packageName) => ({
    name: packageName,
    version: resolveVersion(packageName),
    license: resolveLicense(packageName),
  }))
  .map((item) => ({
    ...item,
    ...(dependencyNotices[item.name]?.(item.version) ?? {}),
  }))

const items = [
  {
    name: 'MySCUT',
    version: packageJson.version,
    license: packageJson.license,
    sourceUrl: packageJson.repository.url.replace(/\.git$/, ''),
    licenseUrl: `${packageJson.repository.url.replace(/\.git$/, '')}/blob/main/LICENSE`,
  },
  ...dependencyItems,
]

const rows = items.map((item) => (
  `  { name: ${quote(item.name)}, version: ${quote(item.version)}, license: ${quote(item.license)}, sourceUrl: ${item.sourceUrl ? quote(item.sourceUrl) : 'null'}, licenseUrl: ${item.licenseUrl ? quote(item.licenseUrl) : 'null'} },`
))
const output = [
  '// Generated by scripts/generateThirdPartyLicenses.mjs. Do not edit manually.',
  '',
  'export const THIRD_PARTY_LICENSES = [',
  ...rows,
  '] as const',
  '',
].join('\n')

writeFileSync(outputPath, output)
console.log(`Generated ${items.length} license entries.`)
